import 'package:raillog/src/models/dashboard_trip_entry.dart';

enum DashboardAchievementKind {
  freeMeal,
  overnightSeat,
  tightTransfer,
  wellPreparedTransfer,
  sevenDayStreak,
  thirtyDayStreak,
  duration24Hours,
  duration48Hours,
  duration72Hours,
  all25Series,
  allEmuSeries,
  allSeatTypes,
  noSeat12Hours,
  hundredTickets,
  midnightBoarding,
  wallFacingSeat,
  hundredStations,
  thousandKilometers,
  airRail,
  railFerry,
  railwayWorkerPassenger,
  verticalChina,
  horizontalChina,
  highSpeedExperiment,
  slowCrawl,
  slowerThanCycling,
  fleetingMoment,
  borderPorts,
  lonelyPlanet,
  hundredThousandKilometers,
  fTrain,
  axleOverheat,
  permanentMagnetPower,
  advantageIsMine,
  platformSubsidence,
  archaeologyTeam,
  strategist,
  eveOfTheStorm,
  tenNumericTrains,
  overnightSleeper,
  tripleTransfer,
  endsOfTheEarth,
  fourFamousNorths,
  youthPriceless,
  zeroDisplacement,
  dreamPath,
  commuterSpecial,
  grandSlam,
  storedUpReward,
  spontaneousTrip,
  redFootprints,
  greatWallWatch,
  icyWorld,
  unnecessaryExtra,
  blessChina,
  snowWelcomesSpring,
  moistensJiangnan,
  facingTheWorld,
  revivalPrototype,
  vibrantJourney,
  multipleChoices,
  publicDisplayOfAffection,
  farsighted,
  oneYuanJourney,
  cardinalStations,
  ancientLetters,
  miniTurnaround,
  verticalSleeper,
  completeTrainLetters,
  blueHorizon,
}

class DashboardAchievement {
  const DashboardAchievement({
    required this.kind,
    required this.title,
    required this.requirement,
    this.unlockedBy,
  });

  final DashboardAchievementKind kind;
  final String title;
  final String requirement;
  final DashboardTripEntry? unlockedBy;

  bool get isUnlocked => unlockedBy != null;
}
